# Generated by Django 6.0.6 on 2026-07-17 05:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_customuser_angelonetotpsecret'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='active_symbol',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='active_timeframe',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
