# Generated by Django 6.0.6 on 2026-07-21 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_customuser_active_symbol_customuser_active_timeframe'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='exnessTerminalPath',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
