# Generated by Django 6.0.6 on 2026-07-21 11:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_customuser_exnessterminalpath'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='exnessTerminalPath',
        ),
    ]
