# Generated by Django 6.0.6 on 2026-07-24 03:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_remove_customuser_exnessterminalpath'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserActiveStrategy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symbol', models.CharField(max_length=50)),
                ('timeframe', models.CharField(max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('strategy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.strategy')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='active_strategies', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'strategy')},
            },
        ),
    ]
