from dataclasses import dataclass, field
from typing import Dict, Any


@dataclass
class TradeSignal:
    """
    Generated by a strategy.

    Contains ONLY the trading idea.
    No money management.
    """

    strategy: str

    symbol: str

    action: str

    entry: float

    pattern: Dict[str, Any] = field(default_factory=dict)